#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/home/dhanya/espnet/tools/python_user_base"
export PATH="/home/dhanya/espnet/tools/python_user_base/bin":${PATH}
export PATH=/home/dhanya/anaconda3/bin:${PATH}
